# Site settings
languages: ["es", "en", "pt"]
exclude_from_localizations: ["assets", "images", "css", "principios"]
title_left    : "Mínimo"
# title_right   : "" # default: ""
description   : "Mínimo es un proyecto que impulsa otra forma de hacer negocios y de pensar el marketing. Este blog es una de las formas para expresarlo."
keywords      : "productos digitales, minimalismo, arte"
url           : https://minimo.io # site url
baseurl       : "" # apply repo name like "/myproject" if used under gh-pages branch, else (under master branch) just leave empty/blank
cover         : "https://minimo.io/assets/minimo-logo-500.png" # image uri like logo/cover image for site seo

google_analytics  : UA-134514520-1
twitter_username  : "minimo_labs"
comments_enabled  : false # if enabled (set to true), please provide your disqus_username
disqus_shortname  : "minimo-io"
postshare_enabled : true

# Build settings
permalink   : /:year/:title/
#permalink   : /:year/:y_day/
markdown    : kramdown
highlighter : rouge

source      : ./
destination : ./_site

# Sass configuration
sass:
  sass_dir  : assets/scss
  style     : compressed # expanded

# Author settings
author:
  name     : "minimo.io"

nicolas_ea:
  name: Nicolás
  email: nicolas@minimo.io
  web: https://minimo.io/nicolas-erramuspe.html

plugins:
  - jekyll-sitemap
  - bourbon
  - jekyll-paginate


exclude: ["thinkspace.gemspec", "about", "gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md", "script"]
